#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
#use_frameworks!
use_modular_headers!
inhibit_all_warnings!

target 'diyplayer' do
    # pod swift
    pod 'Moya', '~>11.0'
    pod 'ObjectMapper', '~>3.3'
    pod 'Kingfisher', '4.1.0'
    pod 'SnapKit', '4.0.0'
    pod 'Charts', '3.0.4'
    pod 'DLRadioButton', '~> 1.4'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire-SwiftyJSON'
    pod 'FreeStreamer'
    # pod objective-c
    pod 'MBProgressHUD'
end
	
